name: Waka Readme
# Documentation: https://github.com/anmol098/waka-readme-stats
on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: 'Baking something cool 🍪'
          COMMIT_USERNAME: 'README Baker'
          SYMBOL_VERSION: 3
          SHOW_LANGUAGE: 'False'
          SHOW_OS: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_EDITORS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_LOC_CHART: 'False'
